name = "OkTexHelper"
uuid = "e85a2721-9ec6-4204-992d-01b2e59f22bb"
authors = ["okatsn <okatsn@gmail.com> and contributors"]
version = "0.2.0"


[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"

[compat]
DataFrames = "1.5.0"
julia = "1.8"

[extras]
CompatHelperLocal = "5224ae11-6099-4aaa-941d-3aab004bd678"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Documenter", "CompatHelperLocal"]
